name: Docker Release
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      version:
        required: true
        description: version to publish
        type: string
    secrets:
      dockerUsername:
        required: true
      dockerToken:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions:
          - IMAGES:
              - holomekc/wiremock-gui:latest-alpine
              - holomekc/wiremock-gui:${{ inputs.version }}-alpine
            CONTEXT: alpine
            PLATFORMS: linux/amd64
          - IMAGES:
              - holomekc/wiremock-gui:latest
              - holomekc/wiremock-gui:${{ inputs.version }}
            CONTEXT: .
            PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.dockerUsername }}
          password: ${{ secrets.dockerToken }}

      - name: Build Wiremock Docker image
        run: docker buildx build ${{ matrix.versions.CONTEXT }} --tag ${{ join(matrix.versions.IMAGES, ' --tag ') }} --build-arg WIREMOCK_VERSION=${{ inputs.version }} --build-arg BUILD_DATE=$(date +'%Y-%m-%d') --build-arg GIT_SHA=$GITHUB_SHA --load

      - name: Test Wiremock Docker image
        run: |
          # latest
          docker container run -d --name test -p 8080:8080 ${{ matrix.versions.IMAGES[0] }}
          timeout 10 bash -c 'while ! curl --fail http://localhost:8080/__admin/; do sleep 1; done'
          timeout 10 bash -c 'while ! curl --fail http://localhost:8080/__admin/webapp; do sleep 1; done'
          timeout 10 bash -c 'while ! curl --fail http://localhost:8080/__admin/webapp/mappings; do sleep 1; done'
          timeout 10 bash -c 'while ! curl --fail http://localhost:8080/__admin/webapp/matched; do sleep 1; done'
          timeout 10 bash -c 'while ! curl --fail http://localhost:8080/__admin/webapp/unmatched; do sleep 1; done'
          timeout 10 bash -c 'while ! curl --fail http://localhost:8080/__admin/webapp/state; do sleep 1; done'
          timeout 10 bash -c 'while ! curl --fail http://localhost:8080/__admin/webapp/files; do sleep 1; done'
          docker container rm -f test

          # version
          docker container run -d --name test -p 8080:8080 ${{ matrix.versions.IMAGES[1] }}
          timeout 10 bash -c 'while ! curl --fail http://localhost:8080/__admin/; do sleep 1; done'
          timeout 10 bash -c 'while ! curl --fail http://localhost:8080/__admin/webapp; do sleep 1; done'
          timeout 10 bash -c 'while ! curl --fail http://localhost:8080/__admin/webapp/mappings; do sleep 1; done'
          timeout 10 bash -c 'while ! curl --fail http://localhost:8080/__admin/webapp/matched; do sleep 1; done'
          timeout 10 bash -c 'while ! curl --fail http://localhost:8080/__admin/webapp/unmatched; do sleep 1; done'
          timeout 10 bash -c 'while ! curl --fail http://localhost:8080/__admin/webapp/state; do sleep 1; done'
          timeout 10 bash -c 'while ! curl --fail http://localhost:8080/__admin/webapp/files; do sleep 1; done'
          docker container rm -f test

      - name: Push wiremock-gui image to Docker HUB
        run: docker buildx build ${{ matrix.versions.CONTEXT }} --tag ${{ join(matrix.versions.IMAGES, ' --tag ') }} --build-arg WIREMOCK_VERSION=${{ inputs.version }} --build-arg BUILD_DATE=$(date +'%Y-%m-%d') --build-arg GIT_SHA=$GITHUB_SHA --platform ${{ matrix.versions.PLATFORMS }} --push
